# Generated by Django 6.0.7 on 2026-08-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0002_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
