# Generated by Django 6.0.7 on 2026-09-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0003_moneyboxexpense_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyfriend',
            name='bed_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
