# Generated by Django 6.0.7 on 2026-09-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0004_alter_familyfriend_bed_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivoresultado',
            name='conteudo_binario',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arquivoresultado',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='resultados/'),
        ),
        migrations.AlterField(
            model_name='arquivoresultado',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
